server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: produtos-service
              uri: lb://produtos-service
              predicates:
                - Path=/produtos/**
            - id: pedidos-service
              uri: lb://pedidos-service
              predicates:
                - Path=/pedidos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/